### ISSUE TITLE
NoClassDefFoundError on execution

### ISSUE THREAD

**Issue by MarkFuller1** [masud-technope/SurfClipse-Replication-Package-WCRE2014#2]
# Expected 
 > java -jar surfclipse-exec.jar -caseNo 20 -query query -strace strace -ccontext ccontext -output search-output -topk 10
 
 Should execute the jar successfully. 

# Current Result
``` java
Exception in thread "Thread: #5" Exception in thread "Thread: #7" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 9 more
Exception in thread "Thread: #2" Exception in thread "Thread: #1" Exception in thread "Thread: #3" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "Thread: #6" Exception in thread "Thread: #4" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "Thread: #0" Exception in thread "Thread: #8" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
Exception in thread "Thread: #9" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at utility.MyTokenizer.process_text_item(MyTokenizer.java:133)
	at utility.MyTokenizer.tokenize_text_item(MyTokenizer.java:30)
	at similarity.CosineSimilarityMeasure.getTokenized_text_content_granularized(CosineSimilarityMeasure.java:62)
	at similarity.CosineSimilarityMeasure.get_cosine_similarity_score(CosineSimilarityMeasure.java:74)
	at scoring.ResultTitleMatcher.get_title_2_title_match_score(ResultTitleMatcher.java:39)
	at scoring.ResultTitleMatcher.calculate_title_match_score(ResultTitleMatcher.java:123)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:66)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.lang.NoClassDefFoundError: net/barenca/jastyle/ASFormatter
	at utility.MyTokenizer.format_the_code(MyTokenizer.java:88)
	at utility.MyTokenizer.tokenize_code_item(MyTokenizer.java:56)
	at scoring.SourceCodeContextMatcher.<init>(SourceCodeContextMatcher.java:25)
	at scoring.ScoreCalculator.calculate_intermediate_scores(ScoreCalculator.java:95)
	at scoring.ScoreCalculator.run(ScoreCalculator.java:51)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: net.barenca.jastyle.ASFormatter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more
Done: 20
Query executed successfully!
Time needed:0s
```

# Attempted Solutions

Using `java -xbootclasspath/a` with the lib folder of the 2 sister repositories. 

Manually altering the jar to include the class definitions and updating the `MANIFEST.MF`

**Comment by diptadas** [comment]
I got the same error for Java 1.13. Changing the Java version to 1.8 solved the issue.

**Comment by masud-technope** [comment]
OK guys, thanks for your interest in this work. I just made the source code public for your convenience. 
https://github.com/masud-technope/SurfClipse-Prototype
Any pull requests or contributions will be greatly appreciated.

Best,
-Masud
